### ISSUE TITLE
Header Element improvment

### ISSUE THREAD

**Issue by AmitKlohan** [megha-n-bodke/GrowMeghaPortfolio#8]
I've one suggestion for this element
- Instead of having two elements one for mobile version and other for desktop, you may use one and arrange the display as per requirement

**Comment by frankfembo** [comment]
## Great work 👍 
- Good PR description ✔️ 
- Your design looks **Awesome** ✔️ 
- No linter errors ✔️ 
>
> I think it can be great if you can as well use a url for icons generation by linking it in the head. eg, search for the googleappis link for Material+Icons or FontAwesome, as alternative for svg's.

**Otherwise everything looks perfectly fine**
